#pragma once
#include "pebble.h"

#define BRIDGE_API_VERSION "1.2"

GColor disconnected_color, main_color, text_color;

enum ReceivingAppMessageKey {
  WATCHAPP_READY_SIGNAL,			// 0
  BRIDGE_IS_LISTENING,				// 1
  MESSAGE_UNIQUE_ID_TO_ACK,			// 2
  ALBUM_KEY,						// 3
  ARTIST_KEY,						// 4
  SONG_KEY,							// 5
  IS_PLAYING_KEY,					// 6
  MESSAGE_LIST_ENTRY_KEY1,			// 7
  MESSAGE_LIST_ENTRY_KEY2,			// 8
  MESSAGE_LIST_ENTRY_KEY3,			// 9
  MESSAGE_LIST_ENTRY_KEY4,			// 10
  MESSAGE_LIST_ENTRY_KEY5,			// 11
  MESSAGE_SENDER_TO_SHOW,			// 12
  MESSAGE_SUBJECT_TO_SHOW,			// 13
  MESSAGE_BODY_TO_SHOW,				// 14
  MESSAGE_ACCOUNTID_TO_SHOW,		// 15
  MESSAGE_MESSAGEID_TO_SHOW,		// 16
  MESSAGE_TO_SHOW_IS_EMAIL,			// 17
  MESSAGE_TO_SHOW_IS_READ,			// 18
  MESSAGE_TO_SHOW_IS_NEW_MESSAGE,	// 19
  CONFIG_KEY_VIBRATION_TYPE,		// 20
  CONFIG_KEY_REPLY1,				// 21
  CONFIG_KEY_REPLY2,				// 22
  CONFIG_KEY_REPLY3,				// 23
  CONFIG_KEY_REPLY4,				// 24
  CONFIG_KEY_REPLY5,				// 25
  CONFIG_KEY_REPLY6,				// 26
  CONFIG_KEY_MAIN_COLOR,			// 27
  CONFIG_KEY_LARGE_FONT,			// 28
  CONFIG_KEY_BACKLIGHT              // 29
};

enum SendingAppMessageKey {
  TRANSACTION_ID_KEY,
  WATCHAPP_STARTED,
  WATCHAPP_STOPPED,
  REFRESH_NEEDED_KEY,
  MUSIC_COMMAND_KEY,
  MESSAGE_ACCOUNTID_KEY,
  MESSAGE_MESSAGEID_KEY,
  MESSAGE_IS_EMAIL_KEY,
  READER_VOICEREPLY_COMMAND_KEY,
  READER_MARKREAD_COMMAND_KEY,
  READER_DELETE_COMMAND_KEY,
  TAKE_NOTE_COMMAND_KEY,
  UPDATE_SETTINGS_KEY, 
  IS_BRIDGE_LISTENING_KEY,
  ACK_THIS_MESSAGE_UNIQUE_ID, //14
  INBOUND_SIZE,
  DOO_COMMAND_KEY
};

enum MusicControlKey {
	MUSIC_PLAY,
	MUSIC_STOP,
	MUSIC_NEXT,
	MUSIC_PREVIOUS,
	MUSIC_VOLUME_UP,
	MUSIC_VOLUME_DOWN
};

enum UpdateRequestKey {
  UPDATE_EMAIL_LIST,
  UPDATE_SMS_LIST,
  UPDATE_MUSIC_METADATA,
  UNSPECIFIED
};

enum MainColor {
	COLOR_FASHION_MAGENTA,
	COLOR_BABY_BLUE_EYES,
	COLOR_KELLY_GREEN,
	COLOR_SUNSET_ORANGE
};